services:
  # Django Backend
  - type: web
    name: quiz-backend
    runtime: python
    buildCommand: ./build.sh
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn quiz_portal.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.2"
